// <auto-generated />
namespace Final.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixedErrorcs1662CanRunNow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedErrorcs1662CanRunNow));
        
        string IMigrationMetadata.Id
        {
            get { return "202105100147573_FixedErrorcs1662CanRunNow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
